### ISSUE TITLE
apt update v1.5.5 wrong version tagging

### ISSUE THREAD

**Issue by tietzsg** [hekmekk/git-team#17]
Hi,

it seems like the version v1.5.5 is "newer" than "1.7.0" due to sorting characters before numbers.

Maybe deleting the version "v1.5.5" is easy?

```
~$ apt list --upgradable -a
Listing... Done
git-team/stable v1.5.5 amd64 [upgradable from: 1.7.0]
git-team/stable,now 1.7.0 amd64 [installed,upgradable to: v1.5.5]
git-team/stable 1.6.0 amd64
git-team/stable 1.5.6-rc1 amd64
git-team/stable 1.5.5 amd64
git-team/stable 1.5.4 amd64
```

**Comment by hekmekk** [comment]
Sorry for the late reply. This seems to be an apt.sourc.es issue, which I have no direct access to. The naming issue in the releases has been fixed. I will contact the maintainer in order to fix this for debian based distros.

**Comment by hekmekk** [comment]
The issue should've been resolved :rocket: Please double check if it works for you now.

**Comment by tietzsg** [comment]
Looks good now
```
~ [100] $ apt list -a git-team
Listing... Done
git-team/stable,now 1.7.0 amd64 [installed]
git-team/stable 1.6.0 amd64
git-team/stable 1.5.6-rc1 amd64
git-team/stable 1.5.5 amd64
git-team/stable 1.5.4 amd64
```
Thanks!
