### ISSUE TITLE
Build for 1.7.0 fails with go 1.18

### ISSUE THREAD

**Issue by gblues** [hekmekk/git-team#20]
# Bug Report

git-team version: 1.7.0
go version: 1.18

## failure description
When attempting to install git-team via homebrew, the `go build` step fails because of outdated dependencies.

## expected behaviour description
git-team should install successfully

While installing with `--HEAD` works, it also brings in other code changes.

proposed workaround:
1. create a new branch off the `v1.7.0` commit
2. apply [this patch](https://github.com/gblues/git-team/commit/4b565b4139f846cbae75e6ad06ad99919809f45a.diff), which fixes the build issues
3. tag the commit with `v1.7.1`
4. update the homebrew formula to v1.7.1
5. on the `main` branch, bump the dev version up to 1.7.2-alpha1 or whatever

**Comment by hekmekk** [comment]
Thank you for bringing this up @gblues and sorry for the late reply. Will look into this as soon as possible.

**Comment by hekmekk** [comment]
[This commit](https://github.com/hekmekk/homebrew-git-team/commit/d43c084b9652eabc540d1c68f054f7ec7e70bd7b) should resolve the issue for now and reflect the current state of the project.
