### ISSUE TITLE
a present `core.hooksPath` setting is ignored

### ISSUE THREAD

**Issue by hekmekk** [hekmekk/git-team#7]
# Bug Report

git-team version: 1.3.4
go version: 1.12

## failure description
The `git config` option `core.hooksPath` is **overriden** on `enable` and then **unset** on `disable`. If it was set before, the respective hooks will be deactivated when git-team is enabled and not re-enabled when git-team is disabled again. This is confusing for users.

## expected behaviour description
Existing hooks in `core.hooksPath` – apart from `prepare-commit-msg` – should be respected.

**Comment by delitescere** [comment]
Could either record a previous value to `/usr/local/etc/git-team/hooks/.original.hookspath` or use a `team.state.previousHooksPath` config value to restore upon `git team disable`.

**Comment by delitescere** [comment]
An updated `proxy.sh` would look like this.

```sh
#!/bin/sh

REAL_GLOBAL_HOOK="$(git config --get team.state.previousHooksPath)/$(basename $0)"

if [ -x "${REAL_GLOBAL_HOOK}" ]; then
  "${REAL_GLOBAL_HOOK}" "$@" || exit $?
else
  REAL_LOCAL_HOOK="$(git rev-parse --show-toplevel)/.git/hooks/$(basename $0)"

  if [ -x "${REAL_LOCAL_HOOK}" ]; then
    "${REAL_LOCAL_HOOK}" "$@" || exit $?
  fi
fi

exit 0
```

Also corrected to only use executable files, and mimic git hooks behaviour in that if a global hook is present, a local hooks is ignored (assuming that the global hooks have logic to execute local hooks when present).

**Comment by hekmekk** [comment]
Thanks for the input. My thoughts were going in a pretty similar direction. Your suggestion for `proxy.sh` looks good!

**Comment by hekmekk** [comment]
Finally closed by https://github.com/hekmekk/git-team/commit/39bb2cc04536174658612bce51fd57547ba8bc35.
