### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by DennisBecker** [hekmekk/git-team#8]
# Feature Request
Please add a changelog in the format described at https://keepachangelog.com/

#### current behaviour
no changelog exists, manually have to check al git commit messages

#### desired behaviour
a changelog can quickly inform you about the changes

## use case / why is this important?
quick overview of changes / features / bugfixes
possibility to get a view with all commits between two versions

**Comment by hekmekk** [comment]
Totally makes sense. Done.
